work in progress

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: CI Pipeline
+name: CI/CD Pipeline
 
 on:
   push:
@@ -6,75 +6,79 @@ on:
       - '**'
 
 jobs:
-  build:
+  tests:
+    name: Test
     runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
 
-      - name: Set up JDK
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
           java-version: '21'
-          distribution: 'temurin'
+          distribution: 'adopt'
 
-      - name: Build project
-        run: ./gradlew build
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
 
-  test:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+      - name: Run tests with coverage
+        working-directory: kudagoAPI
+        run: ./gradlew test jacocoTestReport
 
-      - name: Set up JDK
-        uses: actions/setup-java@v3
+      - name: Upload test coverage report
+        uses: actions/upload-artifact@v3
         with:
-          java-version: '21'
-          distribution: 'temurin'
-
-      - name: Run tests
-        run: ./gradlew test
-
-      - name: Calculate test coverage
-        run: ./gradlew jacocoTestReport
-
-      - name: Upload coverage report
-        uses: actions/upload-artifact@v2
-        with:
-          name: coverage-report
+          name: test-coverage-report
           path: kudagoAPI/build/reports/jacoco/test/jacocoTestReport.xml
 
-  lint:
+  build_and_publish:
+    name: build and Publish Docker Image
     runs-on: ubuntu-latest
-    needs: build
+    needs: [ tests ]
+    if: github.event_name == 'push'
+
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-      - name: Run static code analysis
-        run: ./gradlew check
-
-  docker:
-    runs-on: ubuntu-latest
-    needs: [build, test, lint]
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-
-      - name: Log in to GitHub Container Registry
-        uses: docker/login-action@v2
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
         with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+          java-version: '21'
+          distribution: 'adopt'
 
-      - name: Build Docker image
-        run: docker build -t ghcr.io/${{ github.repository }}/my-app:latest .
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
+
+      - name: Build with Gradle
+        working-directory: kudagoAPI
+        run: ./gradlew clean build -x test
+
+      - name: Set global environment variables
+        id: global_env
+        run: |
+          echo "::set-output name=IMAGE_NAME::${GITHUB_REPOSITORY#*/}"
+          echo "::set-output name=DOCKER_IMAGE_NAME::ghcr.io/${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY#*/}"
+
+      - name: Log in to GitHub Docker registry
+        run: echo "${{ secrets.FJ }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
+
+      - name: Check if JAR file exists
+        run: |
+          if [ ! -f lesson5/build/libs/lesson5.jar ]; then
+            echo "JAR file not found! Check if the build step created the file."
+            exit 1
+          fi
+
+      - name: Build and tag Docker image
+        run: |
+          docker build -t "${{ steps.global_env.outputs.DOCKER_IMAGE_NAME }}:latest" \
+                       -t "${{ steps.global_env.outputs.DOCKER_IMAGE_NAME }}:${GITHUB_SHA::8}" \
+                       -f lesson5/Dockerfile .
 
       - name: Push Docker image to GitHub Packages
-        run: docker push ghcr.io/${{ github.repository }}/my-app:latest
+        run: |
+          docker push "${{ steps.global_env.outputs.DOCKER_IMAGE_NAME }}:latest"
+          docker push "${{ steps.global_env.outputs.DOCKER_IMAGE_NAME }}:${GITHUB_SHA::8}"
